stages:
  - build
  - test

create:
  image: alpine
  stage: build
  script:
    - echo "Building..."
    - mkdir build
    - touch build/new_file.txt
  artifacts:
      paths:
        - build/new_file.txt


test:
  image: alpine
  stage: test
  script:
    - echo "Testing..."
    - if [ -f build/new_file.txt ]; then echo "File exists"; else echo "File does not exist"; exit 1; fi