stages:
  - build
  - test

build_backend:
  image: python:3.12
  stage: build
  script:
    - echo "Debug cwd and files"
    - pwd
    - ls -l
    - echo "Creating virtual environment..."
    - python -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install -r backend/backendAPI/requirements.txt
    - echo "Build step completed"
  artifacts:
    paths:
      - venv/

test_backend:
  image: python:3.12
  stage: test
  dependencies:
    - build_backend
  script:
    - source venv/bin/activate
    - PYTHONPATH=backend/backendAPI pytest backend/backendAPI/tests/
